services:
  sut:
    build:
      context: ..
      dockerfile: .kerno/Dockerfile
    ports:
    - 0:8000
    environment:
      PROJECT_NAME: Small Backend
      VERSION: 1.0.0
      API_V1_STR: /v1
      SECRET_KEY: super-secret-key-for-development-change-in-production
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 11520
      SYSTEM_NAME: small-backend
    labels:
      external-url: http://localhost:{{PORT}}